export const CURRENCIES: Record<string, { symbol: string; name: string; nameAr: string; nameFr: string }> = {
  USD: { symbol: "$", name: "US Dollar", nameAr: "دولار أمريكي", nameFr: "Dollar américain" },
  EUR: { symbol: "€", name: "Euro", nameAr: "يورو", nameFr: "Euro" },
  GBP: { symbol: "£", name: "British Pound", nameAr: "جنيه إسترليني", nameFr: "Livre sterling" },
  // Arab currencies
  SAR: { symbol: "ر.س", name: "Saudi Riyal", nameAr: "ريال سعودي", nameFr: "Riyal saoudien" },
  AED: { symbol: "د.إ", name: "UAE Dirham", nameAr: "درهم إماراتي", nameFr: "Dirham émirati" },
  EGP: { symbol: "ج.م", name: "Egyptian Pound", nameAr: "جنيه مصري", nameFr: "Livre égyptienne" },
  DZD: { symbol: "د.ج", name: "Algerian Dinar", nameAr: "دينار جزائري", nameFr: "Dinar algérien" },
  MAD: { symbol: "د.م", name: "Moroccan Dirham", nameAr: "درهم مغربي", nameFr: "Dirham marocain" },
  TND: { symbol: "د.ت", name: "Tunisian Dinar", nameAr: "دينار تونسي", nameFr: "Dinar tunisien" },
  QAR: { symbol: "ر.ق", name: "Qatari Riyal", nameAr: "ريال قطري", nameFr: "Riyal qatari" },
  KWD: { symbol: "د.ك", name: "Kuwaiti Dinar", nameAr: "دينار كويتي", nameFr: "Dinar koweïtien" },
  BHD: { symbol: "د.ب", name: "Bahraini Dinar", nameAr: "دينار بحريني", nameFr: "Dinar bahreïni" },
  OMR: { symbol: "ر.ع", name: "Omani Rial", nameAr: "ريال عماني", nameFr: "Rial omanais" },
  JOD: { symbol: "د.أ", name: "Jordanian Dinar", nameAr: "دينار أردني", nameFr: "Dinar jordanien" },
  IQD: { symbol: "ع.د", name: "Iraqi Dinar", nameAr: "دينار عراقي", nameFr: "Dinar irakien" },
  LBP: { symbol: "ل.ل", name: "Lebanese Pound", nameAr: "ليرة لبنانية", nameFr: "Livre libanaise" },
  LYD: { symbol: "د.ل", name: "Libyan Dinar", nameAr: "دينار ليبي", nameFr: "Dinar libyen" },
  SYP: { symbol: "ل.س", name: "Syrian Pound", nameAr: "ليرة سورية", nameFr: "Livre syrienne" },
  YER: { symbol: "ر.ي", name: "Yemeni Rial", nameAr: "ريال يمني", nameFr: "Rial yéménite" },
  SDG: { symbol: "ج.س", name: "Sudanese Pound", nameAr: "جنيه سوداني", nameFr: "Livre soudanaise" },
  MRU: { symbol: "أ.م", name: "Mauritanian Ouguiya", nameAr: "أوقية موريتانية", nameFr: "Ouguiya mauritanien" },
  SOS: { symbol: "ش.ص", name: "Somali Shilling", nameAr: "شلن صومالي", nameFr: "Shilling somalien" },
  DJF: { symbol: "ف.ج", name: "Djiboutian Franc", nameAr: "فرنك جيبوتي", nameFr: "Franc djiboutien" },
  KMF: { symbol: "ف.ق", name: "Comorian Franc", nameAr: "فرنك قمري", nameFr: "Franc comorien" },
  PSE: { symbol: "₪", name: "Palestinian", nameAr: "شيكل فلسطيني", nameFr: "Shekel palestinien" },
  // Other currencies
  TRY: { symbol: "₺", name: "Turkish Lira", nameAr: "ليرة تركية", nameFr: "Livre turque" },
  INR: { symbol: "₹", name: "Indian Rupee", nameAr: "روبية هندية", nameFr: "Roupie indienne" },
  PKR: { symbol: "₨", name: "Pakistani Rupee", nameAr: "روبية باكستانية", nameFr: "Roupie pakistanaise" },
  NGN: { symbol: "₦", name: "Nigerian Naira", nameAr: "نيرة نيجيرية", nameFr: "Naira nigérian" },
  CAD: { symbol: "CA$", name: "Canadian Dollar", nameAr: "دولار كندي", nameFr: "Dollar canadien" },
  AUD: { symbol: "A$", name: "Australian Dollar", nameAr: "دولار أسترالي", nameFr: "Dollar australien" },
  JPY: { symbol: "¥", name: "Japanese Yen", nameAr: "ين ياباني", nameFr: "Yen japonais" },
  CNY: { symbol: "¥", name: "Chinese Yuan", nameAr: "يوان صيني", nameFr: "Yuan chinois" },
};

export const COUNTRY_CURRENCY: Record<string, string> = {
  US: "USD", GB: "GBP", SA: "SAR", AE: "AED", EG: "EGP",
  DZ: "DZD", MA: "MAD", TN: "TND", QA: "QAR", KW: "KWD",
  BH: "BHD", OM: "OMR", JO: "JOD", IQ: "IQD", LB: "LBP",
  LY: "LYD", SY: "SYP", YE: "YER", SD: "SDG", MR: "MRU",
  SO: "SOS", DJ: "DJF", KM: "KMF", PS: "PSE",
  TR: "TRY", IN: "INR", PK: "PKR", NG: "NGN", CA: "CAD",
  AU: "AUD", JP: "JPY", CN: "CNY",
  FR: "EUR", DE: "EUR", IT: "EUR", ES: "EUR", NL: "EUR", BE: "EUR", PT: "EUR",
};
